project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - "_targets.R"

website:
  title: "Statistical Rethinking colearning 2023"

  sidebar:
    contents: auto

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    code-line-numbers: false
    code-copy: true
    code-link: true
    code-block-border-left: false
