project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Statistical Rethinking colearning 2023"

  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "Homework"
        href: homework/00-homework-listing.qmd
        contents:
          - href: homework/01-homework.qmd
            text: Homework 01
      - section: "Notes"
        href: notes/00-notes-listing.qmd
        contents:
          - href: notes/01-notes.qmd
            text: Lecture 01
          - href: notes/02-notes.qmd
            text: Lecture 02
          - href: notes/03-notes.qmd
            text: Lecture 03
          - href: notes/04-notes.qmd
            text: Lecture 04
          - href: notes/09-notes.qmd
            text: Lecture 09


format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
