---
title: 'statistical-rethinking-colearning-2023'
output: 
  github_document:
    toc: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

---

Second round of colearning the Statistical Rethinking 
[book](https://xcelab.net/rm/statistical-rethinking/), 2023 [lectures](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus) and 
[homework](https://github.com/rmcelreath/stat_rethinking_2023/tree/main/homework).
The first round of colearning (2022) is available [here](https://github.com/robitalec/statistical-rethinking-colearning-2022).




## Schedule

### Lectures

| Meeting date | Reading  | Lectures  |
| :----------- | :------- | :-------- |
| 26 January   | Chapters 1, 2 and 3 | [1] <[Science Before Statistics](https://www.youtube.com/watch?v=FdnMWdICdRs&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=1)> <[Slides](https://speakerdeck.com/rmcelreath/statistical-rethinking-2023-lecture-01)> <br> [2] <[Garden of Forking Data](https://www.youtube.com/watch?v=R1vcdhPBlXA&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=2)> <[Slides](https://speakerdeck.com/rmcelreath/statistical-rethinking-2023-lecture-02)>
| | Chapter 4 | [3] <[Geocentric Models](https://www.youtube.com/watch?v=tNOu-SEacNU&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=3)> <[Slides](https://speakerdeck.com/rmcelreath/statistical-rethinking-2023-lecture-03)> <br> [4] <[Categories and Curves](https://www.youtube.com/watch?v=F0N4b7K_iYQ&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=4)> <[Slides](https://speakerdeck.com/rmcelreath/statistical-rethinking-2023-lecture-04)>
| | Chapters 5 and 6 |  [5] <[Elemental Confounds](https://www.youtube.com/watch?v=mBEA7PKDmiY&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=5)> <[Slides](https://speakerdeck.com/rmcelreath/statistical-rethinking-2023-lecture-05)> <br> [6] <[Good and Bad Controls](https://www.youtube.com/watch?v=uanZZLlzKHw&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=6)> <[Slides](https://speakerdeck.com/rmcelreath/statistical-rethinking-2023-lecture-06)>
| | Chapters 7 and 8 | [7] Overfitting <br> [8] Interactions
| | Chapters 9, 10 and 11 | [9] Markov chain Monte Carlo <br> [10] Binomial GLMs
| | Chapters 11 and 12 | [11] Poisson GLMs <br> [12] Ordered Categories
| | Chapter 13 | [13] Multilevel Models <br> [14] Multi-Multilevel Models
| | Chapter 14 | [15] Varying Slopes <br> [16] Gaussian Processes
| | Chapter 15 | [17] Measurement Error <br> [18] Missing Data
| | Chapters 16 and 17 | [19] Beyond GLMs: State-space Models, ODEs <br> [20] Horoscopes



### Homework

| Meeting date | Homework    | Solutions | 
| :----------- | :---------- | :-------- |
| 2 February   | [Homework 1](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week01.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week01-solutions.pdf) | 
|              | [Homework 2](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week02.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week02-solutions.pdf) | 
|              | [Homework 3](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week03.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week03-solutions.pdf) | 
|              | [Homework 4](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week04.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week04-solutions.pdf) | 
|              | [Homework 5](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week05.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week05-solutions.pdf) | 
|              | [Homework 6](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week06.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week06-solutions.pdf) | 
|              | [Homework 7](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week07.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week07-solutions.pdf) | 
|              | [Homework 8](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week08.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week08-solutions.pdf) | 
|              | [Homework 9](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week09.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week09-solutions.pdf) | 
|              | [Homework 10](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week10.pdf) | [Solutions](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week10-solutions.pdf) | 



## Participant notes and homework solutions

- [Alec](https://github.com/robitalec/statistical-rethinking-colearning-2023) (this repo)
- 
- 



## Resources

* Lectures: https://github.com/rmcelreath/stat_rethinking_2022#calendar--topical-outline
* Homework: https://github.com/rmcelreath/stat_rethinking_2022/tree/main/homework

Additional material using other packages or languages

* Original R: https://github.com/rmcelreath/rethinking/
* R + Tidyverse + ggplot2 + brms: https://bookdown.org/content/4857/
* Python and PyMC3: Python/PyMC3
* Julia and Turing: https://github.com/StatisticalRethinkingJulia and https://github.com/StatisticalRethinkingJulia/TuringModels.jl

See Richard's comments about these here: https://github.com/rmcelreath/stat_rethinking_2022#original-r-flavor

Also, Alec's notes and solutions of the 2019 material: https://github.com/robitalec/statistical-rethinking and https://www.statistical-rethinking.robitalec.ca/



## Installation

Package specific install directions. We'll update these as we go!

Rethinking

* [`rethinking`](https://github.com/rmcelreath/rethinking#installation)

Stan

* [`cmdstanr`](https://mc-stan.org/cmdstanr/articles/cmdstanr.html)
* [`RStan`](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started)
* [`brms`](r/brms/#how-do-i-install-brms)


Targets

* [`targets`](https://github.com/ropensci/targets/#installation)
* [`stantargets`](https://github.com/ropensci/stantargets/#installation)

V8, needed for the `dagitty` package

* [`V8`](https://github.com/jeroen/v8#installation)




## Code of Conduct

Please note that this project is released with a [Code of
Conduct](CODE_OF_CONDUCT.md). By participating in this project you agree to abide by its terms.
